<?php

namespace Dschini\Cqrs\Bus;

use Dschini\Test\Mock;
use Dschini\Cqrs\Gate;
use Dschini\Cqrs\Command\ClassMapCommandHandlerLoader;
use Dschini\Cqrs\Event\ClassMapEventListenerLoader;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-16 at 23:33:58.
 */
class AbstractBusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractBus
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $classMapCommandHandlerLoader = new ClassMapCommandHandlerLoader();
        $classMapEventListenerLoader = new ClassMapEventListenerLoader();
        $this->object = new Mock\Bus\BusMock($classMapCommandHandlerLoader, $classMapEventListenerLoader);
        $this->object->mapCommand('Dschini\Test\Mock\Command\MockCommand', 'Dschini\Test\Mock\Command\MockCommandHandler');
        Gate::getInstance()->pipe($this->object);
    }

    /**
     * @covers Dschini\Cqrs\Bus\AbstractBus::invokeCommand
     */
    public function testInvokeCommand()
    {
        $mockCommand = new Mock\Command\MockCommand();
        
        $successList = Gate::getInstance()->getBus('mock_bus')->invokeCommand($mockCommand);
        
        $check = array(
            'Dschini\Test\Mock\Command\MockCommand' => true
        );
        
        $this->assertEquals($check, $successList);
    }

    /**
     * @covers Dschini\Cqrs\Bus\AbstractBus::registerEventListener
     * @todo   Implement testRegisterEventListener().
     */
    public function testRegisterEventListener()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Dschini\Cqrs\Bus\AbstractBus::dispatchEvent
     * @todo   Implement testDispatchEvent().
     */
    public function testDispatchEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
