<?php
/*
 * This file is part of the Cqrs package.
 * (c) Manfred Weber <manfred.weber@gmail.com> and Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Cqrs\Bus;

use Test\Mock;
use Cqrs\Gate;
use Test\Mock\Bus\BusMock;
use Cqrs\Command\ClassMapCommandHandlerLoader;
use Cqrs\Gate\GateException;
use Test\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-16 at 23:33:58.
 */
class AbstractBusTest extends TestCase
{

    /**
     * @var AbstractBus
     */
    protected $bus;
    
    /**
     *
     * @var Mock\Event\MockEventListenerLoader 
     */
    protected $mockEventListenerLoader;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $classMapCommandHandlerLoader = new ClassMapCommandHandlerLoader();
        $this->mockEventListenerLoader = new Mock\Event\MockEventListenerLoader();
        $this->mockEventListenerLoader->setMockEventListener(new Mock\Event\MockEventListener());
        $this->bus = new BusMock($classMapCommandHandlerLoader, $this->mockEventListenerLoader);
        try {
            Gate::getInstance()->attach($this->bus);
        } catch( GateException $e){
            echo $e->getMessage();
        }
    }

    /**
     * @covers Cqrs\Bus\AbstractBus::invokeCommand
     */
    public function testInvokeCommand__withCommandHandlerDefinition()
    {
        $this->bus->mapCommand(
            'Test\Mock\Command\MockCommand', 
            array(
                'alias' => 'Test\Mock\Command\MockCommandHandler',
                'method' => 'handleCommand'
            )
        );
        
        $mockCommand = new Mock\Command\MockCommand();
        
        Gate::getInstance()->getBus('mock-bus')->invokeCommand($mockCommand);
        
        //The MockCommandHandler should call $mockCommand->edit(), otherwise
        //$mockCommand->isEdited() returns false
        $this->assertTrue($mockCommand->isEdited());
    }
    
    /**
     * @covers Cqrs\Bus\AbstractBus::invokeCommand
     */
    /*public function testInvokeCommand__withCallableCommandHandler()
    {
        $this->bus->mapCommand(
            'Test\Mock\Command\MockCommand', 
            function($command, $gate) {
                $command->edit();
            }
        );
        
        $mockCommand = new Mock\Command\MockCommand();
        
        Gate::getInstance()->getBus('mock-bus')->invokeCommand($mockCommand);
        
        //The MockCommandHandler should call $mockCommand->edit(), otherwise
        //$mockCommand->isEdited() returns false
        $this->assertTrue($mockCommand->isEdited());
    }*/

    /**
     * @covers Cqrs\Bus\AbstractBus::dispatchEvent
     */
    public function testPublishEvent__withEventListenerDefinition()
    {
        $this->bus->registerEventListener(
            'Test\Mock\Event\MockEvent', 
            array(
                'alias' => 'mock_event_listener',
                'method' => 'onMock'
            )
        );
        
        $mockEvent = new Mock\Event\MockEvent(array('message' => 'it works'));
        
        $this->bus->publishEvent($mockEvent);
        
        $this->assertEquals(
            'it works', 
            $this->mockEventListenerLoader->getEventListener('mock_event_listener')->getMockEventMessage()
        );
    }

    public function testPublishEvent__withInvokableEventListener() {
        $invokableEventListener = new Mock\Event\InvokableEventListener();
        
        $this->bus->registerEventListener('Test\Mock\Event\MockEvent', $invokableEventListener);
        
        $mockEvent = new Mock\Event\MockEvent(array('message' => 'it works'));
        
        $this->bus->publishEvent($mockEvent);
        
        $this->assertEquals(
            'it works', 
            $invokableEventListener->getMockEventMessage()
        );
    }
}
