<?php
/*
 * This file is part of the Cqrs package.
 * (c) Manfred Weber <manfred.weber@gmail.com> and Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Test\Cqrs\Adapter;

use Cqrs\Command\ClassMapCommandHandlerLoader;
use Cqrs\Event\ClassMapEventListenerLoader;
use Cqrs\Gate;
use Doctrine\Common\Annotations\AnnotationRegistry;
use Test\Mock\Bus\BusMock;
use Test\Mock\Command\MockCommand;
use Test\TestCase;
use Cqrs\Adapter\AnnotationAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-16 at 23:33:58.
 */
class AnnotationAdapterTest extends TestCase
{
    /**
     * @covers Cqrs\Adapter\AnnotationAdapter::route
     */
    public function testSendToMultiServices()
    {
        $gate = Gate::getInstance();
        $classMapCommandHandlerLoader = new ClassMapCommandHandlerLoader();
        $classMapEventListenerLoader = new ClassMapEventListenerLoader();
        $bus = new BusMock($classMapCommandHandlerLoader, $classMapEventListenerLoader);
        $gate->pipe($bus);

        $adapter = new AnnotationAdapter();
        $adapter->route($bus,'Test\Mock\Service\MockFooService');
        $adapter->route($bus,'Test\Mock\Service\MockBarService');

        $mockCommand = new MockCommand();
        $bus->invokeCommand($mockCommand);

        $this->markTestIncomplete(
            'Event requires implementation! Also command caching is wrong!'
        );
    }

}
