<?php
/*
 * This file is part of the Cqrs package.
 * (c) Manfred Weber <manfred.weber@gmail.com> and Alexander Miertsch <kontakt@codeliner.ws>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Test\Cqrs\Adapter;

use Cqrs\Command\ClassMapCommandHandlerLoader;
use Cqrs\Event\ClassMapEventListenerLoader;
use Cqrs\Gate;
use Cqrs\Gate\GateException;
use Doctrine\Common\Annotations\AnnotationRegistry;
use Test\Mock\Bus\BusAnnotationMock;
use Test\Mock\Command\MockCommand;
use Test\TestCase;
use Cqrs\Adapter\AnnotationAdapter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-16 at 23:33:58.
 */
class AnnotationAdapterTest extends TestCase
{

    /**
     * @var Gate
     */
    protected $gate;

    /**
     * @var AnnotationAdapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->gate = Gate::getInstance();
        if( !isset( $this->bus ) ){
            $classMapCommandHandlerLoader = new ClassMapCommandHandlerLoader();
            $classMapEventListenerLoader = new ClassMapEventListenerLoader();
            $this->bus = new BusAnnotationMock($classMapCommandHandlerLoader, $classMapEventListenerLoader);
        }
        if( !isset( $this->adapter ) ){
            $this->adapter = new AnnotationAdapter();
        }
    }

    /**
     * @covers Cqrs\Adapter\AnnotationAdapter::allow
     */
    public function testWrongOrMissingAnnotationCommand()
    {
        $this->setExpectedException('Cqrs\Adapter\AdapterException');
        try{
            $this->gate->pipe($this->bus);
        } catch( GateException $e){
            echo $e->getMessage();
        }
        $this->adapter->allow($this->bus,'Test\Mock\Service\MockWrongCommandAnnotationService');
        $this->bus->invokeCommand(new MockCommand());
    }

    /**
     * @covers Cqrs\Adapter\AnnotationAdapter::allow
     */
    public function testSendToMultiServices()
    {
        try{
            $this->gate->pipe($this->bus);
        } catch( GateException $e){
            echo $e->getMessage();
        }
        $this->adapter->allow($this->bus,'Test\Mock\Service\MockAnnotationFooService');
        $this->adapter->allow($this->bus,'Test\Mock\Service\MockAnnotationBarService');
        $this->adapter->allow($this->bus,'Test\Mock\Service\MockAnnotationOutputService');
        $this->bus->invokeCommand(new MockCommand());

    }

}
